# Site settings
title: Lee's Room
email: liyalin1991@live.com
description: > # 牛逼啊.
baseurl: /
encoding: utf-8
url: "http://liyalin.github.io"
twitter_username: LIYALIN1991
github_username:  LIYALIN1991
timezone: Asia/Shanghai

# Build settings
# markdown:

permalink: /:categories/:year/:month/:day/:title